services:
  db:
    image: mysql:8.0
    container_name: db-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dataviser
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "3306:3306"
    networks:
      - dataviser_network
    volumes:
      - mysql_data:/var/lib/mysql

  websocket:
    build: ./websocket_server
    container_name: websocket_server
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_HOST: dataviser
      DATABASE_USER: dev
      DATABASE_PASSWORD: dev
      DATABASE_NAME: dataviser
    ports:
      - "3001:3001"
    networks:
      - dataviser_network

  app:
    build: ./dataviser
    env_file:
      - ./dataviser/.env
    container_name: app-1
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://dev:dev@db:3306/dataviser"
    ports:
      - "3000:3000"
    networks:
      - dataviser_network

networks:
  dataviser_network:
    driver: bridge

volumes:
  mysql_data:
