import "./globals.css";
import StoreProvider from "./store/StoreProvider";

export const metadata = {
  title: "dataviser://",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
/*  <StoreProvider>
 */   <html lang="fr">
        <body>
          {children}
        </body>
      </html>
    /* </StoreProvider> */
  );
}
